openapi: 3.0.0
servers:
  - url: https://api.twitch.tv/helix
    description: Production API
info:
  title: Twitch Helix API
  description: The Twitch API is a RESTful API that lets developers build creative
    integrations for the broader Twitch community. THIS DOCUMENTATION IS NEITHER
    MAINTAINED BY OR AFFILIATED WITH TWITCH
  termsOfService: https://www.twitch.tv/p/en/legal/developer-agreement/
  contact:
    name: TwitchDev
    url: https://dev.twitch.tv/support/
    email: developers@twitch.tv
  version: 2024‑03‑07
paths:
  /channels/commercial:
    post:
      summary: Start Commercial
      description: Starts a commercial on the specified channel.
      tags:
        - Ads
      security:
        - oauth:
            - channel:edit:commercial
  /channels/ads:
    get:
      summary: Get Ad Schedule
      description: Returns ad schedule related information.
      tags:
        - Ads
      security:
        - oauth:
            - channel:read:ads
  /channels/ads/schedule/snooze:
    post:
      summary: Snooze Next Ad
      description: Pushes back the timestamp of the upcoming automatic mid-roll ad by
        5 minutes.
      tags:
        - Ads
      security:
        - oauth:
            - channel:manage:ads
  /analytics/extensions:
    get:
      summary: Get Extension Analytics
      description: Gets an analytics report for one or more extensions.
      tags:
        - Analytics
      security:
        - oauth:
            - analytics:read:extensions
  /analytics/games:
    get:
      summary: Get Game Analytics
      description: Gets an analytics report for one or more games.
      tags:
        - Analytics
      security:
        - oauth:
            - analytics:read:games
  /bits/leaderboard:
    get:
      summary: Get Bits Leaderboard
      description: Gets the Bits leaderboard for the authenticated broadcaster.
      tags:
        - Bits
      security:
        - oauth:
            - bits:read
  /bits/cheermotes:
    get:
      summary: Get Cheermotes
      description: Gets a list of Cheermotes that users can use to cheer Bits.
      tags:
        - Bits
      security:
        - oauth: []
  /extensions/transactions:
    get:
      summary: Get Extension Transactions
      description: Gets an extension’s list of transactions.
      tags:
        - Bits
      security:
        - oauth: []
  /channels:
    get:
      summary: Get Channel Information
      description: Gets information about one or more channels.
      tags:
        - Channels
      security:
        - oauth: []
    patch:
      summary: Modify Channel Information
      description: Updates a channel’s properties.
      tags:
        - Channels
      security:
        - oauth:
            - channel:manage:broadcast
  /channels/editors:
    get:
      summary: Get Channel Editors
      description: Gets the broadcaster’s list editors.
      tags:
        - Channels
      security:
        - oauth:
            - channel:read:editors
  /channels/followed:
    get:
      summary: Get Followed Channels
      description: Gets a list of broadcasters that the specified user follows. You
        can also use this endpoint to see whether a user follows a specific
        broadcaster.
      tags:
        - Channels
      security:
        - oauth:
            - user:read:follows
  /channels/followers:
    get:
      summary: Get Channel Followers
      description: Gets a list of users that follow the specified broadcaster. You can
        also use this endpoint to see whether a specific user follows the
        broadcaster.
      tags:
        - Channels
      security:
        - oauth:
            - moderator:read:followers
  /channel_points/custom_rewards:
    post:
      summary: Create Custom Rewards
      description: Creates a Custom Reward in the broadcaster’s channel.
      tags:
        - Channel Points
      security:
        - oauth:
            - channel:manage:redemptions
    delete:
      summary: Delete Custom Reward
      description: Deletes a custom reward that the broadcaster created.
      tags:
        - Channel Points
      security:
        - oauth:
            - channel:manage:redemptions
    get:
      summary: Get Custom Reward
      description: Gets a list of custom rewards that the specified broadcaster created.
      tags:
        - Channel Points
      security:
        - oauth:
            - channel:read:redemptions
    patch:
      summary: Update Custom Reward
      description: Updates a custom reward.
      tags:
        - Channel Points
      security:
        - oauth:
            - channel:manage:redemptions
  /channel_points/custom_rewards/redemptions:
    get:
      summary: Get Custom Reward Redemption
      description: Gets a list of redemptions for a custom reward.
      tags:
        - Channel Points
      security:
        - oauth:
            - channel:read:redemptions
    patch:
      summary: Update Redemption Status
      description: Updates a redemption’s status.
      tags:
        - Channel Points
      security:
        - oauth:
            - channel:manage:redemptions
  /charity/campaigns:
    get:
      summary: Get Charity Campaign
      description: Gets information about the broadcaster’s active charity campaign.
      tags:
        - Charity
      security:
        - oauth:
            - channel:read:charity
  /charity/donations:
    get:
      summary: Get Charity Campaign Donations
      description: Gets the list of donations that users have made to the
        broadcaster’s active charity campaign.
      tags:
        - Charity
      security:
        - oauth: []
  /chat/chatters:
    get:
      summary: Get Chatters
      description: Gets the list of users that are connected to the broadcaster’s chat
        session.
      tags:
        - Chat
      security:
        - oauth:
            - moderator:read:chatters
  /chat/emotes:
    get:
      summary: Get Channel Emotes
      description: Gets the broadcaster’s list of custom emotes.
      tags:
        - Chat
      security:
        - oauth: []
  /chat/emotes/global:
    get:
      summary: Get Global Emotes
      description: Gets all global emotes.
      tags:
        - Chat
      security:
        - oauth: []
  /chat/emotes/set:
    get:
      summary: Get Emote Sets
      description: Gets emotes for one or more specified emote sets.
      tags:
        - Chat
      security:
        - oauth: []
  /chat/badges:
    get:
      summary: Get Channel Chat Badges
      description: Gets the broadcaster’s list of custom chat badges.
      tags:
        - Chat
      security:
        - oauth: []
  /chat/badges/global:
    get:
      summary: Get Global Chat Badges
      description: Gets Twitch’s list of chat badges.
      tags:
        - Chat
      security:
        - oauth: []
  /chat/settings:
    get:
      summary: Get Chat Settings
      description: Gets the broadcaster’s chat settings.
      tags:
        - Chat
      security:
        - oauth:
            - moderator:read:chat_settings
    patch:
      summary: Update Chat Settings
      description: Updates the broadcaster’s chat settings.
      tags:
        - Chat
      security:
        - oauth:
            - moderator:manage:chat_settings
  /chat/emotes/user:
    get:
      summary: Get User Emotes
      description: BETA Retrieves emotes available to the user across all channels.
      tags:
        - Chat
      security:
        - oauth:
            - user:read:emotes
  /chat/announcements:
    post:
      summary: Send Chat Announcement
      description: Sends an announcement to the broadcaster’s chat room.
      tags:
        - Chat
      security:
        - oauth:
            - moderator:manage:announcements
  /chat/shoutouts:
    post:
      summary: Send a Shoutout
      description: Sends a Shoutout to the specified broadcaster.
      tags:
        - Chat
      security:
        - oauth:
            - moderator:manage:shoutouts
  /chat/messages:
    post:
      summary: Send Chat Message
      description: NEW Sends a message to the broadcaster’s chat room.
      tags:
        - Chat
      security:
        - oauth: []
  /chat/color:
    get:
      summary: Get User Chat Color
      description: Gets the color used for the user’s name in chat.
      tags:
        - Chat
      security:
        - oauth: []
    put:
      summary: Update User Chat Color
      description: Updates the color used for the user’s name in chat.
      tags:
        - Chat
      security:
        - oauth:
            - user:manage:chat_color
  /clips:
    post:
      summary: Create Clip
      description: Creates a clip from the broadcaster’s stream.
      tags:
        - Clips
      security:
        - oauth:
            - clips:edit
    get:
      summary: Get Clips
      description: Gets one or more video clips.
      tags:
        - Clips
      security:
        - oauth: []
  /eventsub/conduits:
    get:
      summary: Get Conduits
      description: NEW Gets the conduits for a client ID.
      tags:
        - Conduits
      security:
        - oauth: []
    post:
      summary: Create Conduits
      description: NEW Creates a new conduit.
      tags:
        - Conduits
      security:
        - oauth: []
    patch:
      summary: Update Conduits
      description: NEW Updates a conduit’s shard count.
      tags:
        - Conduits
      security:
        - oauth: []
    delete:
      summary: Delete Conduit
      description: NEW Deletes a specified conduit.
      tags:
        - Conduits
      security:
        - oauth: []
  /eventsub/conduits/shards:
    get:
      summary: Get Conduit Shards
      description: NEW Gets a lists of all shards for a conduit.
      tags:
        - Conduits
      security:
        - oauth: []
    patch:
      summary: Update Conduit Shards
      description: NEW Updates shard(s) for a conduit.
      tags:
        - Conduits
      security:
        - oauth: []
  /content_classification_labels:
    get:
      summary: Get Content Classification Labels
      description: Gets information about Twitch content classification labels.
      tags:
        - CCLs
      security:
        - oauth: []
  /entitlements/drops:
    get:
      summary: Get Drops Entitlements
      description: Gets an organization’s list of entitlements that have been granted
        to a game, a user, or both.
      tags:
        - Entitlements
      security:
        - oauth: []
    patch:
      summary: Update Drops Entitlements
      description: Updates the Drop entitlement’s fulfillment status.
      tags:
        - Entitlements
      security:
        - oauth: []
  /extensions/configurations:
    get:
      summary: Get Extension Configuration Segment
      description: Gets the specified configuration segment from the specified extension.
      tags:
        - Extensions
      security:
        - oauth: []
    put:
      summary: Set Extension Configuration Segment
      description: Updates a configuration segment.
      tags:
        - Extensions
      security:
        - oauth: []
  /extensions/required_configuration:
    put:
      summary: Set Extension Required Configuration
      description: Updates the extension’s required_configuration string.
      tags:
        - Extensions
      security:
        - oauth: []
  /extensions/pubsub:
    post:
      summary: Send Extension PubSub Message
      description: Sends a message to one or more viewers.
      tags:
        - Extensions
      security:
        - oauth: []
  /extensions/live:
    get:
      summary: Get Extension Live Channels
      description: Gets a list of broadcasters that are streaming live and have
        installed or activated the extension.
      tags:
        - Extensions
      security:
        - oauth: []
  /extensions/jwt/secrets:
    get:
      summary: Get Extension Secrets
      description: Gets an extension’s list of shared secrets.
      tags:
        - Extensions
      security:
        - oauth: []
    post:
      summary: Create Extension Secret
      description: Creates a shared secret used to sign and verify JWT tokens.
      tags:
        - Extensions
      security:
        - oauth: []
  /extensions/chat:
    post:
      summary: Send Extension Chat Message
      description: Sends a message to the specified broadcaster’s chat room.
      tags:
        - Extensions
      security:
        - oauth: []
  /extensions:
    get:
      summary: Get Extensions
      description: Gets information about an extension.
      tags:
        - Extensions
      security:
        - oauth: []
  /extensions/released:
    get:
      summary: Get Released Extensions
      description: Gets information about a released extension.
      tags:
        - Extensions
      security:
        - oauth: []
  /bits/extensions:
    get:
      summary: Get Extension Bits Products
      description: Gets the list of Bits products that belongs to the extension.
      tags:
        - Extensions
      security:
        - oauth: []
    put:
      summary: Update Extension Bits Product
      description: Adds or updates a Bits product that the extension created.
      tags:
        - Extensions
      security:
        - oauth: []
  /eventsub/subscriptions:
    post:
      summary: Create EventSub Subscription
      description: Creates an EventSub subscription.
      tags:
        - EventSub
      security:
        - oauth: []
    delete:
      summary: Delete EventSub Subscription
      description: Deletes an EventSub subscription.
      tags:
        - EventSub
      security:
        - oauth: []
    get:
      summary: Get EventSub Subscriptions
      description: Gets a list of EventSub subscriptions that the client in the access
        token created.
      tags:
        - EventSub
      security:
        - oauth: []
  /games/top:
    get:
      summary: Get Top Games
      description: Gets information about all broadcasts on Twitch.
      tags:
        - Games
      security:
        - oauth: []
  /games:
    get:
      summary: Get Games
      description: Gets information about specified games.
      tags:
        - Games
      security:
        - oauth: []
  /goals:
    get:
      summary: Get Creator Goals
      description: Gets the broadcaster’s list of active goals.
      tags:
        - Goals
      security:
        - oauth:
            - channel:read:goals
  /guest_star/channel_settings:
    get:
      summary: Get Channel Guest Star Settings
      description: BETA Gets the channel settings for configuration of the Guest Star
        feature for a particular host.
      tags:
        - Guest Star
      security:
        - oauth:
            - channel:read:guest_star
            - moderator:read:guest_star
    put:
      summary: Update Channel Guest Star Settings
      description: BETA Mutates the channel settings for configuration of the Guest
        Star feature for a particular host.
      tags:
        - Guest Star
      security:
        - oauth:
            - channel:manage:guest_star
  /guest_star/session:
    get:
      summary: Get Guest Star Session
      description: BETA Gets information about an ongoing Guest Star session for a
        particular channel.
      tags:
        - Guest Star
      security:
        - oauth:
            - channel:read:guest_star
            - moderator:read:guest_star
    post:
      summary: Create Guest Star Session
      description: BETA Programmatically creates a Guest Star session on behalf of the
        broadcaster.
      tags:
        - Guest Star
      security:
        - oauth:
            - channel:manage:guest_star
    delete:
      summary: End Guest Star Session
      description: BETA Programmatically ends a Guest Star session on behalf of the
        broadcaster.
      tags:
        - Guest Star
      security:
        - oauth:
            - channel:manage:guest_star
  /guest_star/invites:
    get:
      summary: Get Guest Star Invites
      description: BETA Provides the caller with a list of pending invites to a Guest
        Star session.
      tags:
        - Guest Star
      security:
        - oauth:
            - channel:read:guest_star
            - moderator:read:guest_star
    post:
      summary: Send Guest Star Invite
      description: BETA Sends an invite to a specified guest on behalf of the
        broadcaster for a Guest Star session in progress.
      tags:
        - Guest Star
      security:
        - oauth:
            - channel:manage:guest_star
            - moderator:manage:guest_star
    delete:
      summary: Delete Guest Star Invite
      description: BETA Revokes a previously sent invite for a Guest Star session.
      tags:
        - Guest Star
      security:
        - oauth:
            - channel:manage:guest_star
            - moderator:manage:guest_star
  /guest_star/slot:
    post:
      summary: Assign Guest Star Slot
      description: BETA Allows a previously invited user to be assigned a slot within
        the active Guest Star session.
      tags:
        - Guest Star
      security:
        - oauth:
            - channel:manage:guest_star
            - moderator:manage:guest_star
    patch:
      summary: Update Guest Star Slot
      description: BETA Allows a user to update the assigned slot for a particular
        user within the active Guest Star session.
      tags:
        - Guest Star
      security:
        - oauth:
            - channel:manage:guest_star
            - moderator:manage:guest_star
    delete:
      summary: Delete Guest Star Slot
      description: BETA Allows a caller to remove a slot assignment from a user
        participating in an active Guest Star session.
      tags:
        - Guest Star
      security:
        - oauth:
            - channel:manage:guest_star
            - moderator:manage:guest_star
  /guest_star/slot_settings:
    patch:
      summary: Update Guest Star Slot Settings
      description: BETA Allows a user to update slot settings for a particular guest
        within a Guest Star session.
      tags:
        - Guest Star
      security:
        - oauth:
            - channel:manage:guest_star
            - moderator:manage:guest_star
  /hypetrain/events:
    get:
      summary: Get Hype Train Events
      description: Gets information about the broadcaster’s current or most recent
        Hype Train event.
      tags:
        - Hype Train
      security:
        - oauth:
            - channel:read:hype_train
  /moderation/enforcements/status:
    post:
      summary: Check AutoMod Status
      description: Checks whether AutoMod would flag the specified message for review.
      tags:
        - Moderation
      security:
        - oauth:
            - moderation:read
  /moderation/automod/message:
    post:
      summary: Manage Held AutoMod Messages
      description: Allow or deny the message that AutoMod flagged for review.
      tags:
        - Moderation
      security:
        - oauth:
            - moderator:manage:automod
  /moderation/automod/settings:
    get:
      summary: Get AutoMod Settings
      description: Gets the broadcaster’s AutoMod settings.
      tags:
        - Moderation
      security:
        - oauth:
            - moderator:read:automod_settings
    put:
      summary: Update AutoMod Settings
      description: Updates the broadcaster’s AutoMod settings.
      tags:
        - Moderation
      security:
        - oauth:
            - moderator:manage:automod_settings
  /moderation/banned:
    get:
      summary: Get Banned Users
      description: Gets all users that the broadcaster banned or put in a timeout.
      tags:
        - Moderation
      security:
        - oauth:
            - moderation:read
  /moderation/bans:
    post:
      summary: Ban User
      description: Bans a user from participating in a broadcaster’s chat room or puts
        them in a timeout.
      tags:
        - Moderation
      security:
        - oauth:
            - moderator:manage:banned_users
    delete:
      summary: Unban User
      description: Removes the ban or timeout that was placed on the specified user.
      tags:
        - Moderation
      security:
        - oauth:
            - moderator:manage:banned_users
  /moderation/unban_requests:
    get:
      summary: Get Unban Requests
      description: BETA Gets a list of unban requests for a broadcaster’s channel.
      tags:
        - Moderation
      security:
        - oauth:
            - moderator:read:unban_requests
    patch:
      summary: Resolve Unban Requests
      description: BETA Resolves an unban request by approving or denying it.
      tags:
        - Moderation
      security:
        - oauth:
            - moderator:manage:unban_requests
  /moderation/blocked_terms:
    get:
      summary: Get Blocked Terms
      description: Gets the broadcaster’s list of non-private, blocked words or phrases.
      tags:
        - Moderation
      security:
        - oauth:
            - moderator:read:blocked_terms
    post:
      summary: Add Blocked Term
      description: Adds a word or phrase to the broadcaster’s list of blocked terms.
      tags:
        - Moderation
      security:
        - oauth:
            - moderator:manage:blocked_terms
    delete:
      summary: Remove Blocked Term
      description: Removes the word or phrase from the broadcaster’s list of blocked terms.
      tags:
        - Moderation
      security:
        - oauth:
            - moderator:manage:blocked_terms
  /moderation/chat:
    delete:
      summary: Delete Chat Messages
      description: Removes a single chat message or all chat messages from the
        broadcaster’s chat room.
      tags:
        - Moderation
      security:
        - oauth:
            - moderator:manage:chat_messages
  /moderation/channels:
    get:
      summary: Get Moderated Channels
      description: Gets a list of channels that the specified user has moderator
        privileges in.
      tags:
        - Moderation
      security:
        - oauth:
            - user:read:moderated_channels
  /moderation/moderators:
    get:
      summary: Get Moderators
      description: Gets all users allowed to moderate the broadcaster’s chat room.
      tags:
        - Moderation
      security:
        - oauth:
            - moderation:read
    post:
      summary: Add Channel Moderator
      description: Adds a moderator to the broadcaster’s chat room.
      tags:
        - Moderation
      security:
        - oauth:
            - channel:manage:moderators
    delete:
      summary: Remove Channel Moderator
      description: Removes a moderator from the broadcaster’s chat room.
      tags:
        - Moderation
      security:
        - oauth:
            - channel:manage:moderators
  /channels/vips:
    get:
      summary: Get VIPs
      description: Gets a list of the broadcaster’s VIPs.
      tags:
        - Moderation
      security:
        - oauth:
            - channel:read:vips
            - channel:manage:vips
    post:
      summary: Add Channel VIP
      description: Adds the specified user as a VIP in the broadcaster’s channel.
      tags:
        - Moderation
      security:
        - oauth:
            - channel:manage:vips
    delete:
      summary: Remove Channel VIP
      description: Removes the specified user as a VIP in the broadcaster’s channel.
      tags:
        - Moderation
      security:
        - oauth:
            - channel:manage:vips
  /moderation/shield_mode:
    put:
      summary: Update Shield Mode Status
      description: Activates or deactivates the broadcaster’s Shield Mode.
      tags:
        - Moderation
      security:
        - oauth:
            - moderator:manage:shield_mode
    get:
      summary: Get Shield Mode Status
      description: Gets the broadcaster’s Shield Mode activation status.
      tags:
        - Moderation
      security:
        - oauth:
            - moderator:read:shield_mode
  /polls:
    get:
      summary: Get Polls
      description: Gets a list of polls that the broadcaster created.
      tags:
        - Polls
      security:
        - oauth:
            - channel:read:polls
    post:
      summary: Create Poll
      description: Creates a poll that viewers in the broadcaster’s channel can vote on.
      tags:
        - Polls
      security:
        - oauth:
            - channel:manage:polls
    patch:
      summary: End Poll
      description: End an active poll.
      tags:
        - Polls
      security:
        - oauth:
            - channel:manage:polls
  /predictions:
    get:
      summary: Get Predictions
      description: Gets a list of Channel Points Predictions that the broadcaster created.
      tags:
        - Predictions
      security:
        - oauth:
            - channel:read:predictions
    post:
      summary: Create Prediction
      description: Create a Channel Points Prediction.
      tags:
        - Predictions
      security:
        - oauth:
            - channel:manage:predictions
    patch:
      summary: End Prediction
      description: Locks, resolves, or cancels a Channel Points Prediction.
      tags:
        - Predictions
      security:
        - oauth:
            - channel:manage:predictions
  /raids:
    post:
      summary: Start a raid
      description: Raid another channel by sending the broadcaster’s viewers to the
        targeted channel.
      tags:
        - Raids
      security:
        - oauth:
            - channel:manage:raids
    delete:
      summary: Cancel a raid
      description: Cancel a pending raid.
      tags:
        - Raids
      security:
        - oauth:
            - channel:manage:raids
  /schedule:
    get:
      summary: Get Channel Stream Schedule
      description: Gets the broadcaster’s streaming schedule.
      tags:
        - Schedule
      security:
        - oauth: []
  /schedule/icalendar:
    get:
      summary: Get Channel iCalendar
      description: Gets the broadcaster’s streaming schedule as an iCalendar.
      tags:
        - Schedule
      security:
        - oauth: []
  /schedule/settings:
    patch:
      summary: Update Channel Stream Schedule
      description: Updates the broadcaster’s schedule settings, such as scheduling a
        vacation.
      tags:
        - Schedule
      security:
        - oauth:
            - channel:manage:schedule
  /schedule/segment:
    post:
      summary: Create Channel Stream Schedule Segment
      description: Adds a single or recurring broadcast to the broadcaster’s streaming
        schedule.
      tags:
        - Schedule
      security:
        - oauth:
            - channel:manage:schedule
    patch:
      summary: Update Channel Stream Schedule Segment
      description: Updates a scheduled broadcast segment.
      tags:
        - Schedule
      security:
        - oauth:
            - channel:manage:schedule
    delete:
      summary: Delete Channel Stream Schedule Segment
      description: Deletes a broadcast from the broadcaster’s streaming schedule.
      tags:
        - Schedule
      security:
        - oauth:
            - channel:manage:schedule
  /search/categories:
    get:
      summary: Search Categories
      description: Gets the games or categories that match the specified query.
      tags:
        - Search
      security:
        - oauth: []
  /search/channels:
    get:
      summary: Search Channels
      description: Gets the channels that match the specified query and have streamed
        content within the past 6 months.
      tags:
        - Search
      security:
        - oauth: []
  /streams/key:
    get:
      summary: Get Stream Key
      description: Gets the channel’s stream key.
      tags:
        - Streams
      security:
        - oauth:
            - channel:read:stream_key
  /streams:
    get:
      summary: Get Streams
      description: Gets a list of all streams.
      tags:
        - Streams
      security:
        - oauth: []
  /streams/followed:
    get:
      summary: Get Followed Streams
      description: Gets the list of broadcasters that the user follows and that are
        streaming live.
      tags:
        - Streams
      security:
        - oauth:
            - user:read:follows
  /streams/markers:
    post:
      summary: Create Stream Marker
      description: Adds a marker to a live stream.
      tags:
        - Streams
      security:
        - oauth:
            - channel:manage:broadcast
    get:
      summary: Get Stream Markers
      description: Gets a list of markers from the user’s most recent stream or from
        the specified VOD/video.
      tags:
        - Streams
      security:
        - oauth:
            - user:read:broadcast
  /subscriptions:
    get:
      summary: Get Broadcaster Subscriptions
      description: Gets a list of users that subscribe to the specified broadcaster.
      tags:
        - Subscriptions
      security:
        - oauth:
            - channel:read:subscriptions
  /subscriptions/user:
    get:
      summary: Check User Subscription
      description: Checks whether the user subscribes to the broadcaster’s channel.
      tags:
        - Subscriptions
      security:
        - oauth:
            - user:read:subscriptions
  /tags/streams:
    get:
      summary: Get All Stream Tags
      description: Gets the list of all stream tags that Twitch defines. You can also
        filter the list by one or more tag IDs.
      tags:
        - Tags
      security:
        - oauth: []
  /streams/tags:
    get:
      summary: Get Stream Tags
      description: Gets the list of stream tags that the broadcaster or Twitch added
        to their channel.
      tags:
        - Tags
      security:
        - oauth: []
  /teams/channel:
    get:
      summary: Get Channel Teams
      description: Gets the list of Twitch teams that the broadcaster is a member of.
      tags:
        - Teams
      security:
        - oauth: []
  /teams:
    get:
      summary: Get Teams
      description: Gets information about the specified Twitch team.
      tags:
        - Teams
      security:
        - oauth: []
  /users:
    get:
      summary: Get Users
      description: Gets information about one or more users.
      tags:
        - Users
      security:
        - oauth:
            - user:read:email
    put:
      summary: Update User
      description: Updates the user’s information.
      tags:
        - Users
      security:
        - oauth:
            - user:edit
  /users/blocks:
    get:
      summary: Get User Block List
      description: Gets the list of users that the broadcaster has blocked.
      tags:
        - Users
      security:
        - oauth:
            - user:read:blocked_users
    put:
      summary: Block User
      description: Blocks the specified user from interacting with or having contact
        with the broadcaster.
      tags:
        - Users
      security:
        - oauth:
            - user:manage:blocked_users
    delete:
      summary: Unblock User
      description: Removes the user from the broadcaster’s list of blocked users.
      tags:
        - Users
      security:
        - oauth:
            - user:manage:blocked_users
  /users/extensions/list:
    get:
      summary: Get User Extensions
      description: Gets a list of all extensions (both active and inactive) that the
        broadcaster has installed.
      tags:
        - Users
      security:
        - oauth:
            - user:read:broadcast
  /users/extensions:
    get:
      summary: Get User Active Extensions
      description: Gets the active extensions that the broadcaster has installed for
        each configuration.
      tags:
        - Users
      security:
        - oauth:
            - channel:manage:extensions
            - user:read:broadcast
    put:
      summary: Update User Extensions
      description: Updates an installed extension’s information.
      tags:
        - Users
      security:
        - oauth:
            - channel:manage:extensions
  /videos:
    get:
      summary: Get Videos
      description: Gets information about one or more published videos.
      tags:
        - Videos
      security:
        - oauth: []
    delete:
      summary: Delete Videos
      description: Deletes one or more videos.
      tags:
        - Videos
      security:
        - oauth:
            - channel:manage:videos
  /whispers:
    post:
      summary: Send Whisper
      description: Sends a whisper message to the specified user.
      tags:
        - Whispers
      security:
        - oauth:
            - user:manage:whispers
components:
  securitySchemes:
    oauth:
      type: oauth2
      description: Twitch APIs use OAuth 2.0 access tokens to access resources. If
        you’re not already familiar with the specification, reading it may help
        you better understand how to get access tokens to use with the Twitch
        API.
      flows:
        implicit:
          authorizationUrl: https://id.twitch.tv/oauth2/authorize
          scopes:
            channel:edit:commercial: Run commercials on a channel.
            channel:read:ads: Read the ads schedule and details on your channel.
            channel:manage:ads: Manage ads schedule on a channel.
            analytics:read:extensions: View analytics data for the Twitch Extensions owned
              by the authenticated account.
            analytics:read:games: View analytics data for the games owned by the
              authenticated account.
            bits:read: View Bits information for a channel.
            channel:manage:broadcast: Manage a channel’s broadcast configuration, including
              updating channel configuration and managing stream markers and
              stream tags.
            channel:read:editors: View a list of users with the editor role for a channel.
            user:read:follows: View the list of channels a user follows.
            moderator:read:followers: Read the followers of a broadcaster.
            channel:manage:redemptions: Manage Channel Points custom rewards and their
              redemptions on a channel.
            channel:read:redemptions: View Channel Points custom rewards and their
              redemptions on a channel.
            channel:read:charity: Read charity campaign details and user donations on your channel.
            moderator:read:chatters: View the chatters in a broadcaster’s chat room.
            moderator:read:chat_settings: View a broadcaster’s chat room settings.
            user:read:emotes: View emotes available to a user
            moderator:manage:chat_settings: Manage a broadcaster’s chat room settings.
            moderator:manage:announcements: Send announcements in channels where you have the moderator role.
            moderator:manage:shoutouts: Manage a broadcaster’s shoutouts.
            user:manage:chat_color: Update the color used for the user’s name in chat.
            clips:edit: Manage Clips for a channel.
            channel:read:goals: View Creator Goals for a channel.
            channel:read:guest_star: Read Guest Star details for your channel.
            moderator:read:guest_star: Read Guest Star details for channels where you are a
              Guest Star moderator.
            channel:manage:guest_star: Manage Guest Star for your channel.
            moderator:manage:guest_star: Manage Guest Star for channels where you are a
              Guest Star moderator.
            channel:read:hype_train: View Hype Train information for a channel.
            moderation:read: View a channel’s moderation data including Moderators, Bans,
              Timeouts, and Automod settings.
            moderator:manage:automod: Manage messages held for review by AutoMod in channels
              where you are a moderator.
            moderator:read:automod_settings: View a broadcaster’s AutoMod settings.
            moderator:manage:automod_settings: Manage a broadcaster’s AutoMod settings.
            moderator:manage:banned_users: Ban and unban users.
            moderator:read:unban_requests: View a broadcaster’s unban requests.
            moderator:manage:unban_requests: Manage a broadcaster’s unban requests.
            moderator:read:blocked_terms: View a broadcaster’s list of blocked terms.
            moderator:manage:blocked_terms: Manage a broadcaster’s list of blocked terms.
            moderator:manage:chat_messages: Delete chat messages in channels where you have the moderator role
            user:read:moderated_channels: Read the list of channels you have moderator privileges in.
            channel:manage:moderators: Add or remove the moderator role from users in your channel.
            channel:read:vips: Read the list of VIPs in your channel.
            channel:manage:vips: Add or remove the VIP role from users in your channel.
            moderator:manage:shield_mode: Manage a broadcaster’s Shield Mode status.
            moderator:read:shield_mode: View a broadcaster’s Shield Mode status.
            channel:read:polls: View a channel’s polls.
            channel:manage:polls: Manage a channel’s polls.
            channel:read:predictions: View a channel’s Channel Points Predictions.
            channel:manage:predictions: Manage of channel’s Channel Points Predictions
            channel:manage:raids: Manage a channel raiding another channel.
            channel:manage:schedule: Manage a channel’s stream schedule.
            channel:read:stream_key: View an authorized user’s stream key.
            user:read:broadcast: View a user’s broadcasting configuration, including
              Extension configurations.
            channel:read:subscriptions: View a list of all subscribers to a channel and
              check if a user is subscribed to a channel.
            user:read:subscriptions: View if an authorized user is subscribed to specific channels.
            user:read:email: View a user’s email address.
            user:edit: Manage a user object.
            user:read:blocked_users: View the block list of a user.
            user:manage:blocked_users: Manage the block list of a user.
            channel:manage:extensions: Manage a channel’s Extension configuration, including
              activating Extensions.
            channel:manage:videos: Manage a channel’s videos, including deleting videos.
            user:manage:whispers: Read whispers that you send and receive, and send whispers
              on your behalf.
        authorizationCode:
          authorizationUrl: https://id.twitch.tv/oauth2/authorize
          tokenUrl: https://id.twitch.tv/oauth2/token
          scopes:
            channel:edit:commercial: Run commercials on a channel.
            channel:read:ads: Read the ads schedule and details on your channel.
            channel:manage:ads: Manage ads schedule on a channel.
            analytics:read:extensions: View analytics data for the Twitch Extensions owned
              by the authenticated account.
            analytics:read:games: View analytics data for the games owned by the
              authenticated account.
            bits:read: View Bits information for a channel.
            channel:manage:broadcast: Manage a channel’s broadcast configuration, including
              updating channel configuration and managing stream markers and
              stream tags.
            channel:read:editors: View a list of users with the editor role for a channel.
            user:read:follows: View the list of channels a user follows.
            moderator:read:followers: Read the followers of a broadcaster.
            channel:manage:redemptions: Manage Channel Points custom rewards and their
              redemptions on a channel.
            channel:read:redemptions: View Channel Points custom rewards and their
              redemptions on a channel.
            channel:read:charity: Read charity campaign details and user donations on your channel.
            moderator:read:chatters: View the chatters in a broadcaster’s chat room.
            moderator:read:chat_settings: View a broadcaster’s chat room settings.
            user:read:emotes: View emotes available to a user
            moderator:manage:chat_settings: Manage a broadcaster’s chat room settings.
            moderator:manage:announcements: Send announcements in channels where you have the moderator role.
            moderator:manage:shoutouts: Manage a broadcaster’s shoutouts.
            user:manage:chat_color: Update the color used for the user’s name in chat.
            clips:edit: Manage Clips for a channel.
            channel:read:goals: View Creator Goals for a channel.
            channel:read:guest_star: Read Guest Star details for your channel.
            moderator:read:guest_star: Read Guest Star details for channels where you are a
              Guest Star moderator.
            channel:manage:guest_star: Manage Guest Star for your channel.
            moderator:manage:guest_star: Manage Guest Star for channels where you are a
              Guest Star moderator.
            channel:read:hype_train: View Hype Train information for a channel.
            moderation:read: View a channel’s moderation data including Moderators, Bans,
              Timeouts, and Automod settings.
            moderator:manage:automod: Manage messages held for review by AutoMod in channels
              where you are a moderator.
            moderator:read:automod_settings: View a broadcaster’s AutoMod settings.
            moderator:manage:automod_settings: Manage a broadcaster’s AutoMod settings.
            moderator:manage:banned_users: Ban and unban users.
            moderator:read:unban_requests: View a broadcaster’s unban requests.
            moderator:manage:unban_requests: Manage a broadcaster’s unban requests.
            moderator:read:blocked_terms: View a broadcaster’s list of blocked terms.
            moderator:manage:blocked_terms: Manage a broadcaster’s list of blocked terms.
            moderator:manage:chat_messages: Delete chat messages in channels where you have the moderator role
            user:read:moderated_channels: Read the list of channels you have moderator privileges in.
            channel:manage:moderators: Add or remove the moderator role from users in your channel.
            channel:read:vips: Read the list of VIPs in your channel.
            channel:manage:vips: Add or remove the VIP role from users in your channel.
            moderator:manage:shield_mode: Manage a broadcaster’s Shield Mode status.
            moderator:read:shield_mode: View a broadcaster’s Shield Mode status.
            channel:read:polls: View a channel’s polls.
            channel:manage:polls: Manage a channel’s polls.
            channel:read:predictions: View a channel’s Channel Points Predictions.
            channel:manage:predictions: Manage of channel’s Channel Points Predictions
            channel:manage:raids: Manage a channel raiding another channel.
            channel:manage:schedule: Manage a channel’s stream schedule.
            channel:read:stream_key: View an authorized user’s stream key.
            user:read:broadcast: View a user’s broadcasting configuration, including
              Extension configurations.
            channel:read:subscriptions: View a list of all subscribers to a channel and
              check if a user is subscribed to a channel.
            user:read:subscriptions: View if an authorized user is subscribed to specific channels.
            user:read:email: View a user’s email address.
            user:edit: Manage a user object.
            user:read:blocked_users: View the block list of a user.
            user:manage:blocked_users: Manage the block list of a user.
            channel:manage:extensions: Manage a channel’s Extension configuration, including
              activating Extensions.
            channel:manage:videos: Manage a channel’s videos, including deleting videos.
            user:manage:whispers: Read whispers that you send and receive, and send whispers
              on your behalf.
        clientCredentials:
          tokenUrl: https://id.twitch.tv/oauth2/token
          scopes: {}
