on: [push, pull_request]

jobs:
  Test:
    runs-on: ubuntu-latest
    name: Check for Docs Updates
    steps:
      - uses: actions/checkout@v2
      - name: Swagger-cli
        uses: mpetrunic/swagger-cli-action@v1.0.0
        with:
          command: "validate ./swagger.yaml"
