name: Check Swagger Definition
on: 
  pull_request:
    branches:
    - main

jobs:
  Test:
    runs-on: ubuntu-latest
    name: Check Swagger definition
    steps:
      - uses: actions/checkout@v2
      - name: Swagger-cli
        uses: mpetrunic/swagger-cli-action@v1.0.0
        with:
          command: "validate ./swagger.yaml"
