name: Automatic Update Check
on:
  schedule:
      - cron:  '0 1 * * *'
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - '.github/workflows/update.yml'

jobs:
  UpdateCheck:
    runs-on: ubuntu-latest
    environment: prod
    name: Check for Docs Updates
    steps:
      - uses: actions/checkout@v2
      - name: Check for Updates and pull docs
        id: hello
        uses: katzen48/TwitchOpenApiGenerator@v0.8
      # Use the output from the `hello` step
      - name: Swagger-cli
        uses: mpetrunic/swagger-cli-action@v1.0.0
        with:
          command: "validate ./swagger.yaml"
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: update docs
          title: Update Docs
          branch: update-docs
          base: main
          delete-branch: true
      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          token: ${{ secrets.PAT }}
          merge-method: squash
