on:
  schedule:
      - cron:  '0 1 * * *'

jobs:
  UpdateCheck:
    runs-on: ubuntu-latest
    name: Check for Docs Updates
    steps:
      - uses: actions/checkout@v2
      - name: Check for Updates and pull docs
        id: hello
        uses: katzen48/TwitchOpenApiGenerator@v0.1
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
      - name: Swagger-cli
        uses: mpetrunic/swagger-cli-action@v1.0.0
        with:
          command: "validate ./swagger.yaml"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.11.0
        with:
          commit-message: update docs
          title: Update Docs
          branch: update-docs
          base: main
