name: Upload Swagger Definition
on:
  push: 
    branches:
    - main
jobs:
  upload:
    runs-on: ubuntu-latest
    environment: prod
    name: Upload Swagger Definition
    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install SwaggerHub-CLI
        run: npm i -g swaggerhub-cli
        shell: bash
      - name: Unpublish Current Version
        env:
          SWAGGERHUB_API_KEY: ${{ secrets.SWAGGERHUB_API_KEY }}
        run: swaggerhub api:unpublish Katzen48/TwitchAPI/Helix
        shell: bash
      - name: Upload to SwaggerHub
        env:
          SWAGGERHUB_API_KEY: ${{ secrets.SWAGGERHUB_API_KEY }}
        run: swaggerhub api:update Katzen48/TwitchAPI/Helix --file swagger.yaml --published=publish --setdefault 
        shell: bash
